# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/9636D17436D15639/University/CE-Github-Repository/Neural-Soup-in-a-Zynq-Pot/src/HelloWorld/HelloWorld.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
# IP: The module: 'design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/9636D17436D15639/University/CE-Github-Repository/Neural-Soup-in-a-Zynq-Pot/src/HelloWorld/HelloWorld.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/9636D17436D15639/University/CE-Github-Repository/Neural-Soup-in-a-Zynq-Pot/src/HelloWorld/HelloWorld.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
# IP: The module: 'design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/9636D17436D15639/University/CE-Github-Repository/Neural-Soup-in-a-Zynq-Pot/src/HelloWorld/HelloWorld.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
